# Generated by Django 5.1.3 on 2024-12-04 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_remove_products_product_image_images_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
