# Generated by Django 5.1.4 on 2024-12-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0006_products_added_at_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='products',
            new_name='product',
        ),
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='confirm', max_length=100),
        ),
    ]
